# Generated by Django 4.2.30 on 2026-09-09 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='线路名称')),
                ('code', models.CharField(max_length=12, unique=True, verbose_name='线路编号')),
                ('color', models.CharField(default='#1677ff', max_length=7, verbose_name='线路颜色')),
            ],
            options={
                'verbose_name': '地铁线路',
                'verbose_name_plural': '地铁线路',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='站点名称')),
                ('sequence', models.PositiveIntegerField(verbose_name='线路顺序')),
                ('x', models.PositiveIntegerField(default=50, verbose_name='地图 X 坐标')),
                ('y', models.PositiveIntegerField(default=50, verbose_name='地图 Y 坐标')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='subway.line', verbose_name='所属线路')),
            ],
            options={
                'verbose_name': '地铁站点',
                'verbose_name_plural': '地铁站点',
                'ordering': ['line__code', 'sequence'],
            },
        ),
        migrations.AddConstraint(
            model_name='station',
            constraint=models.UniqueConstraint(fields=('line', 'sequence'), name='unique_line_sequence'),
        ),
    ]
