# Generated by Django 4.2.30 on 2026-09-09 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subway', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='is_transfer',
            field=models.BooleanField(default=False, verbose_name='是否换乘站'),
        ),
        migrations.AlterField(
            model_name='station',
            name='x',
            field=models.PositiveIntegerField(default=50, verbose_name='地图 X 百分比'),
        ),
        migrations.AlterField(
            model_name='station',
            name='y',
            field=models.PositiveIntegerField(default=50, verbose_name='地图 Y 百分比'),
        ),
    ]
