# Generated by Django 4.2.30 on 2026-09-11 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subway', '0002_station_is_transfer_alter_station_x_alter_station_y'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_time', models.PositiveIntegerField(verbose_name='通行时间(分钟)')),
                ('from_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='out_edges', to='subway.station', verbose_name='起点站')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subway.line', verbose_name='所属线路')),
                ('to_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_edges', to='subway.station', verbose_name='终点站')),
            ],
            options={
                'verbose_name': '站间边',
                'verbose_name_plural': '站间边',
            },
        ),
    ]
