# Generated by Django 4.2.30 on 2026-09-16 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subway', '0003_edge'),
    ]

    operations = [
        migrations.AddField(
            model_name='edge',
            name='distance_km',
            field=models.FloatField(blank=True, null=True, verbose_name='真实站间距(公里)'),
        ),
    ]
